name: Elixir CI

env:
  ELIXIR_VERSION: 1.10.3
  OTP_VERSION: 23.x
  APP_VERSION: 0.6.9

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }} # Define the elixir version [required]
          otp-version: ${{ env.OTP_VERSION }} # Define the OTP version [required]

      - name: Get deps cache
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: deps
          key: deps-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ env.APP_VERSION }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ env.APP_VERSION }}-

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: plts-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ env.APP_VERSION }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            plts-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ env.APP_VERSION }}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Tests
        run: mix test

      - name: Check Typespec
        run: mix dialyzer

      - name: Build Code Coverage Report
        run: mix coveralls.json

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
